service:
  extends:
        - asset
  content:

    Author:

    name:
        label: Name
        required: true
        type: text

    version:
        label: Version
        required: true
        type: text
        regex: ([0-9]+\.{0,1})*
        validationMessage: Please follow the format x.x.x

    description:
        label: Description
        required: false
        type: text
        inherits: false