service:
  extends:
        - asset
  content:

    Author: #use a single case for keys #if this concept is used, key will be the label.

    name: #if any field doesnt have a label use the key
        label: Name
        required: true
        type: String

    version:
        label: Version
        required: true
        type: String
        validate: ([0-9]+\.{0,1})*
        validateMessage: Please follow the format x.x.x

    description:
        label: Description
        required: false
        type: string
        inherits: false